
language: node_js
node_js:
  - "4.2"

services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server

before_script:
  - npm install -g mocha
  - sleep 15
